### ISSUE TITLE
Unknown enchantment 'twm:swift_sneak' - console message

### ISSUE THREAD

**Issue by xanthian** [Osmiooo/wildmod#167]
```
<![CDATA[Couldn't parse loot table minecraft:chests/ancient_city]]>
<![CDATA[com.google.gson.JsonSyntaxException: Unknown enchantment 'twm:swift_sneak'
	at net.minecraft.class_109$class_110.method_17933(class_109.java:137)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_109$class_110.method_490(class_109.java:137)
	at net.minecraft.class_109$class_110.method_530(class_109.java:111)
	at net.minecraft.class_120$class_123.method_528(class_120.java:99)
	at net.minecraft.class_120$class_123.method_517(class_120.java:88)
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at net.minecraft.class_3518.method_15291(class_3518.java:448)
	at net.minecraft.class_3518.method_15283(class_3518.java:466)
	at net.minecraft.class_85$class_90.method_441(class_85.java:149)
	at net.minecraft.class_85$class_90.method_424(class_85.java:129)
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86)
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74)
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at net.minecraft.class_3518.method_15291(class_3518.java:448)
	at net.minecraft.class_3518.method_15272(class_3518.java:456)
	at net.minecraft.class_55$class_57.method_358(class_55.java:173)
	at net.minecraft.class_55$class_57.deserialize(class_55.java:169)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at net.minecraft.class_3518.method_15291(class_3518.java:448)
	at net.minecraft.class_3518.method_15283(class_3518.java:466)
	at net.minecraft.class_52$class_54.method_340(class_52.java:213)
	at net.minecraft.class_52$class_54.deserialize(class_52.java:209)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at net.minecraft.class_60.method_20711(class_60.java:44)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at net.minecraft.class_60.method_20712(class_60.java:42)
	at net.minecraft.class_60.method_18788(class_60.java:17)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.class_1255.method_18857(class_1255.java:134)
	at net.minecraft.class_310.method_29604(class_310.java:2154)
	at net.minecraft.class_310.method_29610(class_310.java:2003)
	at net.minecraft.class_310.method_29606(class_310.java:1943)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:436)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:342)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:273)
	at net.minecraft.class_350.method_25402(class_350.java:359)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:220)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)]]
```

**Comment by AViewFromTheTop** [comment]
> I also have this issue, but I think it is because 1.18.1 doesn’t support custom structures. That’s my best guess.
> 
> the unknown enchantment part could be a custom structure error or a code error, or an incompatibility with another mod.

It's some random loot table that wasn't deleted prior to release, it contains non-existent stuff (swift sneak) and throws that error

If I'm right, someone already fixed this a little while ago
