### ISSUE TITLE
Sculk Sensor/Shrieker Crash

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#90]
admittedly, i was spamming ravagers on top of them to see if there would be a crash. i'm pretty sure this was caused by overloading threads lol

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 30/01/2022, 09:50
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 65
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.rehash(ObjectOpenCustomHashSet.java:829)
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.add(ObjectOpenCustomHashSet.java:322)
	at net.minecraft.world.tick.ChunkTickScheduler.scheduleTick(ChunkTickScheduler.java:67)
	at net.minecraft.world.tick.WorldTickScheduler.scheduleTick(WorldTickScheduler.java:89)
	at net.minecraft.world.WorldAccess.createAndScheduleBlockTick(WorldAccess.java:47)
	at net.minecraft.block.SculkSensorBlock.setActive(SculkSensorBlock.java:261)
	at net.minecraft.block.entity.SculkSensorBlockEntity.accept(SculkSensorBlockEntity.java:65)
	at net.minecraft.world.event.listener.SculkSensorListener.tick(SculkSensorListener.java:64)
	at net.minecraft.block.SculkSensorBlock.method_32905(SculkSensorBlock.java:215)
	at net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk.java:659)
	at net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk.java:713)
	at net.minecraft.world.World.tickBlockEntities(World.java:477)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:365)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:823)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:99)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.rehash(ObjectOpenCustomHashSet.java:829)
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.add(ObjectOpenCustomHashSet.java:322)
	at net.minecraft.world.tick.ChunkTickScheduler.scheduleTick(ChunkTickScheduler.java:67)
	at net.minecraft.world.tick.WorldTickScheduler.scheduleTick(WorldTickScheduler.java:89)
	at net.minecraft.world.WorldAccess.createAndScheduleBlockTick(WorldAccess.java:47)
	at net.minecraft.block.SculkSensorBlock.setActive(SculkSensorBlock.java:261)
	at net.minecraft.block.entity.SculkSensorBlockEntity.accept(SculkSensorBlockEntity.java:65)
	at net.minecraft.world.event.listener.SculkSensorListener.tick(SculkSensorListener.java:64)
	at net.minecraft.block.SculkSensorBlock.method_32905(SculkSensorBlock.java:215)
	at net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk.java:659)
	at net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk.java:713)
	at net.minecraft.world.World.tickBlockEntities(World.java:477)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:365)

-- Block entity being ticked --
Details:
	Name: minecraft:sculk_sensor // net.minecraft.block.entity.SculkSensorBlockEntity
	Block: Block{minecraft:sculk_sensor}[power=4,sculk_sensor_phase=active,waterlogged=false]
	Block location: World: (-370,-17,618), Section: (at 14,15,10 in -24,-2,38; chunk contains blocks -384,-64,608 to -369,319,623), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
	Block: Block{minecraft:sculk_sensor}[power=4,sculk_sensor_phase=active,waterlogged=false]
	Block location: World: (-370,-17,618), Section: (at 14,15,10 in -24,-2,38; chunk contains blocks -384,-64,608 to -369,319,623), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
Stacktrace:
	at net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk.java:659)
	at net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk.java:713)
	at net.minecraft.world.World.tickBlockEntities(World.java:477)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:365)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:823)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:99)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Player850'/9, l='ServerLevel[twm]', x=-383.08, y=-16.93, z=612.33]]
	Chunk stats: 6150
	Level dimension: minecraft:overworld
	Level spawn location: World: (-112,71,0), Section: (at 0,7,0 in -7,4,0; chunk contains blocks -112,-64,0 to -97,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 735172 game time, 6000 day time
	Level name: twm
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:823)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:99)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1013414536 bytes (966 MiB) / 2682257408 bytes (2558 MiB) up to 4282384384 bytes (4084 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700X Eight-Core Processor         
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.13023.1012
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28108.18
	Virtual memory used (MB): 22546.82
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 575.94
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.0.5+03d159cfc8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.1
		twm: The Wild Mod 0.6-dev
	Server Running: true
	Player Count: 1 / 8; [ServerPlayerEntity['Player850'/9, l='ServerLevel[twm]', x=-383.08, y=-16.93, z=612.33]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
```

**Comment by AViewFromTheTop** [comment]
Once the latest commit builds, would you be able to test this again?

**Comment by MerpisMe** [comment]
> Once the latest commit builds, would you be able to test this again?

yep, just tested it and it's fixed
